-- =====================================================================
-- CMS NGUONHANG1688 - BUỔI 1: Auth/RBAC + Tỷ giá + Thang bảng phí
-- DB: PostgreSQL 14+   |   Chạy lại nhiều lần được (IF NOT EXISTS)
-- Tham chiếu SRS: REQ-1.1 ~ 1.4 (Auth, Tỷ giá), REQ-9.1 (Thang bảng phí)
-- =====================================================================

-- ---------- 1. ROLES (RBAC) ------------------------------------------
-- Tách bảng để thêm vai trò mới bằng INSERT, không phải sửa code (SRS B.4.3)
CREATE TABLE IF NOT EXISTS roles (
    id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(30)  NOT NULL UNIQUE,      -- ADMIN, SALE, ...
    name        VARCHAR(100) NOT NULL,
    description TEXT
);

-- ---------- 2. USERS --------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    email         VARCHAR(255),
    full_name     VARCHAR(150) NOT NULL,
    phone         VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,           -- Argon2id (SRS B.4.2)
    role_id       SMALLINT     NOT NULL REFERENCES roles(id),
    balance       NUMERIC(18,2) NOT NULL DEFAULT 0, -- số dư ví (dùng ở buổi sau)
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'LOCKED'))
);
-- username / email không phân biệt hoa thường
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username_lower ON users (lower(username));
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email_lower    ON users (lower(email)) WHERE email IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_users_role_id ON users (role_id);
CREATE INDEX IF NOT EXISTS ix_users_status  ON users (status);

-- ---------- 3. REFRESH TOKENS ----------------------------------------
-- Lưu jti của refresh token để: xoay vòng (rotation), thu hồi khi logout,
-- phát hiện dùng lại token cũ.
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    jti        VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user_id ON refresh_tokens (user_id);

-- ---------- 4. EXCHANGE RATES (lịch sử tỷ giá - REQ-1.2, 1.3) ---------
-- Chỉ INSERT, không UPDATE: mỗi lần đổi tỷ giá là 1 dòng mới.
-- Tỷ giá hiện hành = dòng mới nhất của từng currency_code.
-- rate = số VNĐ cho 1 đơn vị ngoại tệ (vd 1 CNY = 3920 VNĐ)
CREATE TABLE IF NOT EXISTS exchange_rates (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency_code VARCHAR(3)    NOT NULL,           -- CNY, USD
    rate          NUMERIC(18,4) NOT NULL,
    note          VARCHAR(255),
    created_by    BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_exchange_rates_code CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_exchange_rates_rate CHECK (rate > 0)
);
CREATE INDEX IF NOT EXISTS ix_exchange_rates_lookup
    ON exchange_rates (currency_code, created_at DESC, id DESC);

-- ---------- 5. FEE CONFIGS (thang bảng phí - REQ-9.1) ----------------
-- fee_type: mã loại phí tự do (A-Z, 0-9, _) -> thêm loại phí mới không cần sửa code
--   Đã dùng: PURCHASE_SERVICE_FEE (phí mua hàng), INTL_SHIPPING_FEE (phí vận chuyển QT),
--            INSPECTION_FEE (phí kiểm đếm), WOODEN_CRATE_FEE (phí đóng gỗ)
-- unit: PERCENT | VND | VND_PER_KG | VND_PER_M3 | VND_PER_ITEM | VND_PER_PACKAGE
-- tier_min/tier_max: khoảng áp dụng của bậc thang (NULL = không giới hạn)
--   PURCHASE_SERVICE_FEE -> theo giá trị đơn (VNĐ); VND_PER_KG -> theo kg; VND_PER_M3 -> theo m3
--   Khoảng theo kiểu [tier_min, tier_max)
-- effective_date: ngày bắt đầu hiệu lực; cùng bậc thang có nhiều dòng thì lấy dòng
--   có effective_date mới nhất <= hôm nay (lịch sử phí giữ nguyên để đối soát)
CREATE TABLE IF NOT EXISTS fee_configs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fee_type       VARCHAR(50)   NOT NULL,
    description    VARCHAR(255),
    value          NUMERIC(18,4) NOT NULL,
    unit           VARCHAR(20)   NOT NULL,
    tier_min       NUMERIC(18,4),
    tier_max       NUMERIC(18,4),
    effective_date DATE          NOT NULL DEFAULT ((now() AT TIME ZONE 'Asia/Ho_Chi_Minh')::date),
    is_active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_by     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_fee_configs_type  CHECK (fee_type ~ '^[A-Z][A-Z0-9_]{1,49}$'),
    CONSTRAINT ck_fee_configs_unit  CHECK (unit IN ('PERCENT','VND','VND_PER_KG','VND_PER_M3','VND_PER_ITEM','VND_PER_PACKAGE')),
    CONSTRAINT ck_fee_configs_value CHECK (value >= 0),
    CONSTRAINT ck_fee_configs_tier  CHECK (tier_min IS NULL OR tier_max IS NULL OR tier_max > tier_min),
    CONSTRAINT ck_fee_configs_pct   CHECK (unit <> 'PERCENT' OR value <= 100)
);
CREATE INDEX IF NOT EXISTS ix_fee_configs_lookup
    ON fee_configs (fee_type, is_active, effective_date DESC);
