-- Buổi 2: REQ-3.1 đến REQ-3.6. Áp dụng cho cả database mới và database Buổi 1.
BEGIN;

CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL CHECK (code ~ '^[A-Z0-9][A-Z0-9_.-]{0,49}$'),
    name VARCHAR(150) NOT NULL CHECK (length(btrim(name)) > 0),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(), CHECK (code ~ '^[A-Z]{2}$')
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_countries_code ON countries (lower(code));

CREATE TABLE IF NOT EXISTS units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL CHECK (code ~ '^[A-Z0-9][A-Z0-9_.-]{0,49}$'),
    name VARCHAR(150) NOT NULL CHECK (length(btrim(name)) > 0),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_units_code ON units (lower(code));

CREATE TABLE IF NOT EXISTS package_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL CHECK (code ~ '^[A-Z0-9][A-Z0-9_.-]{0,49}$'),
    name VARCHAR(150) NOT NULL CHECK (length(btrim(name)) > 0),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_package_types_code ON package_types (lower(code));

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL CHECK (code ~ '^[A-Z0-9][A-Z0-9_.-]{0,49}$'),
    name VARCHAR(150) NOT NULL CHECK (length(btrim(name)) > 0),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_categories_code ON categories (lower(code));

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(50) NOT NULL CHECK (sku ~ '^[A-Z0-9][A-Z0-9_.-]{0,49}$'),
    name VARCHAR(255) NOT NULL CHECK (length(btrim(name)) > 0),
    reference_price NUMERIC(18,4) NOT NULL CHECK (reference_price >= 0),
    currency_code VARCHAR(3) NOT NULL DEFAULT 'CNY' CHECK (currency_code IN ('CNY','USD','VND')),
    source_url VARCHAR(2048),
    image_url VARCHAR(2048),
    description TEXT,
    origin_country_id BIGINT REFERENCES countries(id),
    shipping_country_id BIGINT REFERENCES countries(id),
    unit_id BIGINT REFERENCES units(id),
    package_type_id BIGINT REFERENCES package_types(id),
    category_id BIGINT REFERENCES categories(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_products_sku ON products (lower(sku));
CREATE INDEX IF NOT EXISTS ix_products_category ON products (category_id);
CREATE INDEX IF NOT EXISTS ix_products_origin_country ON products (origin_country_id);
CREATE INDEX IF NOT EXISTS ix_products_shipping_country ON products (shipping_country_id);
CREATE INDEX IF NOT EXISTS ix_products_unit ON products (unit_id);
CREATE INDEX IF NOT EXISTS ix_products_package_type ON products (package_type_id);

CREATE TABLE IF NOT EXISTS brand_rights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_name VARCHAR(150) NOT NULL CHECK (length(btrim(brand_name)) > 0),
    holder_name VARCHAR(255) NOT NULL CHECK (length(btrim(holder_name)) > 0),
    right_type VARCHAR(30) NOT NULL CHECK (right_type IN ('COPYRIGHT','DISTRIBUTION_AUTHORIZATION')),
    product_id BIGINT REFERENCES products(id),
    category_id BIGINT REFERENCES categories(id),
    document_url VARCHAR(2048),
    valid_from DATE,
    valid_until DATE,
    note TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_brand_right_target CHECK ((product_id IS NOT NULL) <> (category_id IS NOT NULL)),
    CONSTRAINT ck_brand_right_dates CHECK (valid_until IS NULL OR valid_from IS NULL OR valid_until >= valid_from)
);
CREATE INDEX IF NOT EXISTS ix_brand_rights_product ON brand_rights (product_id);
CREATE INDEX IF NOT EXISTS ix_brand_rights_category ON brand_rights (category_id);
COMMIT;
